- name: Apply SSH Configuration
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
  notify: Restart SSH

- name: Test deployment
  debug:
    msg: "CI/CD deployment test successful!"

  name: Deploy to Local Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # Use the self-hosted runner
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i inventory.ini update_fleet.yml

