---
- name: Deploy to Local Server
  hosts: all
  become: true

  tasks:
    - name: Apply SSH Configuration
      ansible.builtin.template:
        src: sshd_config.j2
        dest: /etc/ssh/sshd_config
        mode: '0644'
      become: yes

    - name: Test deployment
      ansible.builtin.debug:
        msg: "CI/CD deployment test successful!"

  handlers:
    - name: Restart SSH
      ansible.builtin.service:
        name: ssh
        state: restarted
      become: yes
