name: Fleet Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 192.168.68.100 >> ~/.ssh/known_hosts
          ssh-keyscan 192.168.68.101 >> ~/.ssh/known_hosts

      - name: Deploy to Home Server
        run: |
          ssh keith@192.168.68.100 "cd ~/fleet-configs && git pull && ansible-playbook update_fleet.yml"

      - name: Deploy to Raspberry Pi
        run: |
          ssh keith@192.168.68.101 "cd ~/fleet-configs && git pull && ansible-playbook update_fleet.yml"
